import os

AUTO_TOKENIZER_MODEL = os.getenv("AUTO_TOKENIZER_MODEL")
AUTO_MODEL_FOR_SEQ_2_SEQ_LM_MODEL = os.getenv("AUTO_MODEL_FOR_SEQ_2_SEQ_LM_MODEL")

TOOTBOT_ACCESS_TOKEN = os.getenv("TOOTBOT_ACCESS_TOKEN")
TOOTBOT_API_BASE_URL = os.getenv("TOOTBOT_API_BASE_URL")
